version: '3.3'

services:
  git:
    image: gitea/gitea:latest
    ports:
      - "3000:3000"
    networks:
      - git_network
    volumes:
      - nfs_git:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always

networks:
  git_network:
    driver: bridge

volumes:
  nfs_git:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.56.12,rw
      device: ":/nfs/git"
