RAM = 2000
CPU = 3

Vagrant.configure("2") do |config|
    config.vm.define "lb" do |lb|
        lb.vm.box = "debian/buster64"
        lb.vm.provision :shell, path: "bootstrap.sh"
        lb.vm.network "private_network", ip: "192.168.56.15"
        lb.vm.provider "virtualbox" do |v|
            v.memory = RAM
            v.cpus = CPU
        end
    end
end