version: '3.3'

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: example.com
    container_name: mailserver
    env_file: mailserver.env
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
    ports:
      - "25:25"      # SMTP
      - "143:143"    # IMAP
      - "587:587"    # Submission
      - "993:993"    # Secure IMAP
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - mail_network

networks:
  mail_network:
    driver: bridge
