version: '3.3'

services:
  web:
    build: .
    environment:
      db_host: db
      db_user: simeon
      db_password_file: /run/secrets/db_password

    volumes:
      - .:/app

    depends_on:
      - db
    secrets:
      - db_password
    networks:
      - internal

  db:
    image: mysql:8.0
     
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_HOST: simeon
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db_data:/var/lib/msql

    secrets:
      - db_password
      - db_root_password
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html

    depends_on:
      - web
    networks:
      - internal
      - external

volumes:
  db_data:
networks:
  internal:
  external:
secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt


