---
- hosts: all
  become: true  
  tasks:
    - name: Update package index
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package index
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Update package index
      pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: Install Python 3
      apt:
        name: python3-psutil
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Python 3
      dnf:
        name: python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Python 3
      pacman:
        name: python
        state: present
      when: ansible_os_family == "Archlinux"